/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module counter_3bit(ctr, clk, rst);
  output [2:0] ctr;
  wire [2:0] ctr;
  input clk;
  wire clk;
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [2:0] _12_;
  wire [2:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(_07_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(_11_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand2_1 _19_ (
    .A(_07_),
    .B(_08_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(_07_),
    .B(_08_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(_09_),
    .B(_10_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(_11_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(_11_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(clk),
    .D(_12_[0]),
    .Q(ctr[0]),
    .RESET_B(_14_)
  );
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(clk),
    .D(_13_[1]),
    .Q(ctr[1]),
    .RESET_B(_15_)
  );
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(clk),
    .D(_13_[2]),
    .Q(ctr[2]),
    .RESET_B(_16_)
  );
  assign _12_[2:1] = ctr[2:1];
  assign _13_[0] = _12_[0];
  assign _07_ = ctr[0];
  assign _08_ = ctr[1];
  assign _13_[1] = _02_;
  assign _09_ = ctr[2];
  assign _13_[2] = _03_;
  assign _12_[0] = _01_;
  assign _11_ = rst;
  assign _14_ = _04_;
  assign _15_ = _05_;
  assign _16_ = _06_;
endmodule

module mux_8_1(f, sel, i);
  output f;
  wire f;
  input [2:0] sel;
  wire [2:0] sel;
  input [7:0] i;
  wire [7:0] i;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  sky130_fd_sc_hd__mux4_2 _45_ (
    .A0(_33_),
    .A1(_35_),
    .A2(_37_),
    .A3(_39_),
    .S0(_43_),
    .S1(_44_),
    .X(_40_)
  );
  sky130_fd_sc_hd__mux4_2 _46_ (
    .A0(_32_),
    .A1(_34_),
    .A2(_36_),
    .A3(_38_),
    .S0(_43_),
    .S1(_44_),
    .X(_41_)
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(_41_),
    .A1(_40_),
    .S(_42_),
    .X(_31_)
  );
  assign _44_ = sel[2];
  assign _42_ = sel[0];
  assign _43_ = sel[1];
  assign _39_ = i[7];
  assign _38_ = i[6];
  assign _37_ = i[5];
  assign _36_ = i[4];
  assign _35_ = i[3];
  assign _34_ = i[2];
  assign _33_ = i[1];
  assign _32_ = i[0];
  assign f = _31_;
endmodule

module sequential_select(out, start, master_rst, mux_in, clk);
  output out;
  wire out;
  input start;
  wire start;
  input master_rst;
  wire master_rst;
  input [7:0] mux_in;
  wire [7:0] mux_in;
  input clk;
  wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [2:0] ctr_out;
  wire rst;
  wire [2:0] sel;
  wire start_up;
  sky130_fd_sc_hd__clkinv_1 _14_ (
    .A(_04_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and2_0 _15_ (
    .A(_03_),
    .B(_12_),
    .X(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(_05_),
    .B(_06_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__and3b_1 _17_ (
    .A_N(_05_),
    .B(_06_),
    .C(_04_),
    .X(_08_)
  );
  sky130_fd_sc_hd__o21a_1 _18_ (
    .A1(_07_),
    .A2(_08_),
    .B1(_12_),
    .X(_09_)
  );
  counter_3bit ctr_unit (
    .clk(start_up),
    .ctr(ctr_out),
    .rst(rst)
  );
  mux_8_1 mux_unit (
    .f(out),
    .i(mux_in),
    .sel({ sel[2], ctr_out[1], sel[0] })
  );
  assign sel[1] = ctr_out[1];
  assign _03_ = clk;
  assign _12_ = start;
  assign start_up = _13_;
  assign _05_ = ctr_out[1];
  assign _06_ = ctr_out[2];
  assign sel[2] = _11_;
  assign _04_ = ctr_out[0];
  assign sel[0] = _10_;
  assign _07_ = master_rst;
  assign rst = _09_;
endmodule
