/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module mux_8_1(f, sel, i);
  output f;
  wire f;
  input [2:0] sel;
  wire [2:0] sel;
  input [7:0] i;
  wire [7:0] i;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  sky130_fd_sc_hd__mux4_2 _45_ (
    .A0(_33_),
    .A1(_35_),
    .A2(_37_),
    .A3(_39_),
    .S0(_43_),
    .S1(_44_),
    .X(_40_)
  );
  sky130_fd_sc_hd__mux4_2 _46_ (
    .A0(_32_),
    .A1(_34_),
    .A2(_36_),
    .A3(_38_),
    .S0(_43_),
    .S1(_44_),
    .X(_41_)
  );
  sky130_fd_sc_hd__mux2_1 _47_ (
    .A0(_41_),
    .A1(_40_),
    .S(_42_),
    .X(_31_)
  );
  assign _44_ = sel[2];
  assign _42_ = sel[0];
  assign _43_ = sel[1];
  assign _39_ = i[7];
  assign _38_ = i[6];
  assign _37_ = i[5];
  assign _36_ = i[4];
  assign _35_ = i[3];
  assign _34_ = i[2];
  assign _33_ = i[1];
  assign _32_ = i[0];
  assign f = _31_;
endmodule
