/* Generated by Yosys 0.60+8 (git sha1 0e31e389f, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module counter_3bit(ctr, clk, rst);
  output [2:0] ctr;
  reg [2:0] ctr = 3'h0;
  input clk;
  wire clk;
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [2:0] _08_;
  wire [2:0] _09_;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(_04_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(_04_),
    .B(_05_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(_04_),
    .B(_05_),
    .X(_02_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(_06_),
    .B(_07_),
    .Y(_03_)
  );
  always @(posedge clk, posedge rst)
    if (rst) ctr[0] <= 1'h0;
    else ctr[0] <= _08_[0];
  always @(posedge clk, posedge rst)
    if (rst) ctr[1] <= 1'h0;
    else ctr[1] <= _09_[1];
  always @(posedge clk, posedge rst)
    if (rst) ctr[2] <= 1'h0;
    else ctr[2] <= _09_[2];
  assign _08_[2:1] = ctr[2:1];
  assign _09_[0] = _08_[0];
  assign _04_ = ctr[0];
  assign _05_ = ctr[1];
  assign _09_[1] = _02_;
  assign _06_ = ctr[2];
  assign _09_[2] = _03_;
  assign _08_[0] = _01_;
endmodule
